### ISSUE TITLE
after installing via package manager, app is not showing in Apps

### ISSUE THREAD

**Issue by R-and-all** [tomwpublic/hubitat_broadlink#10]
If I install via package manager, the app doesn't appear, no devices are added.

It does show under package manager to repair or uninstall.

What am I doing wrong?

**Comment by tomwpublic** [comment]
You have to create Virtual Devices and install and configure the App.  There are some instructions in my readme, starting at this point:  https://github.com/tomwpublic/hubitat_broadlink#virtual-device-configuration-instructions

**Comment by R-and-all** [comment]
sorry for delay in replying to this. 
I put the kit away when not working, however just reset it up and its great.
Thanks for all your efforts on this.
