### ISSUE TITLE
automatic broadlink

### ISSUE THREAD

**Issue by lewisward1** [tomwpublic/hubitat_broadlink#12]
Hi Tom - thanks for writing a cool app that can control broad link - ive just set it up and can now finally push commands to make my blinds go up and down.

I have a question - how do i invoke the command from an automation rule ? 

Kind Regards
Lewis

**Comment by tomwpublic** [comment]
Here's an example, using Rule Machine:  https://community.hubitat.com/t/broadlink-ir-rf-remotes-integration-rm3-mini-rm-pro-rm4-mini-pro/98827/171

**Comment by lewisward1** [comment]
Thanks mate Sent from my iPhoneOn 28 Mar 2023, at 18:56, tomwpublic ***@***.***> wrote:﻿
Here's an example, using Rule Machine:  https://community.hubitat.com/t/broadlink-ir-rf-remotes-integration-rm3-mini-rm-pro-rm4-mini-pro/98827/171

**Comment by lewisward1** [comment]
Hi Tom 

This worked a treat thanks so much.

Do you have a donation page i can contribute to ?

Kind Regards
Lewis

**Comment by tomwpublic** [comment]
Thank you for offering, but I don't accept donations for this work. If you'd like to pay it forward, please find a way to help someone in need in your local community.
